### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [mikecrowe/mp3chop#1]
Dear @mikecrowe, could you be so kind to roll out a binary for Windows 7 x64? I'm not a developer, but a regular user, so there's a high chance that something will go wrong if compiling it myself.

**Comment by mikecrowe** [comment]
I'm afraid that I'm not really in a position to release binaries, especially for Windows. You might have more luck finding binaries for ffmpeg. See the "Alternatives" section of [`README.md`](https://gitlab.com/mp3chop/mp3chop/-/blob/main/README.md?ref_type=heads).
